"""Tests for mapping/docs_pages.py: generating docs/mappings/*.md pages.

Uses small `.sssom.tsv` fixture files written to `tmp_path` via
`mapping.io.write_sssom_tsv` (the real `sssom-py` writer), never the real
`build/mappings/omop-onz-g.sssom.tsv` or any live ontology/network access,
per AGENTS.md's testing conventions.
"""

from __future__ import annotations

from pathlib import Path

from linkml_runtime.utils.metamodelcore import URI

from sssom_rosetta.mapping.docs_pages import (
    generate_mapping_page,
    generate_mapping_pages,
)
from sssom_rosetta.mapping.io import write_sssom_tsv
from sssom_rosetta.models.sssom import Mapping, MappingSet

MAPPING_SET_ID = URI("https://example.org/mappings/omop-onz-g")
LICENSE = URI("https://creativecommons.org/publicdomain/zero/1.0/")

CURIE_MAP = {
    "omop": "https://w3id.org/omop/ontology#",
    "onz-g": "http://purl.org/ozo/onz-g#",
}


def _mapping(**overrides: object) -> Mapping:
    fields: dict[str, object] = {
        "subject_id": "omop:Person",
        "predicate_id": "skos:exactMatch",
        "object_id": "onz-g:Client",
        "mapping_justification": "semapv:ManualMappingCuration",
        "confidence": 0.9,
        "subject_label": "Person",
        "object_label": "Client",
    }
    fields.update(overrides)
    return Mapping(**fields)


def _mapping_set(*mappings: Mapping) -> MappingSet:
    return MappingSet(
        mapping_set_id=MAPPING_SET_ID,
        license=LICENSE,
        curie_map=CURIE_MAP,
        mappings=list(mappings),
    )


def _write_tsv(build_dir: Path, name: str, mapping_set: MappingSet) -> Path:
    tsv_path = build_dir / f"{name}.sssom.tsv"
    write_sssom_tsv(mapping_set, tsv_path)
    return tsv_path


# --- generate_mapping_page -------------------------------------------------


def test_generate_mapping_page_includes_generated_header_and_content(
    tmp_path: Path,
) -> None:
    tsv_path = _write_tsv(tmp_path, "omop-onz-g", _mapping_set(_mapping()))

    page = generate_mapping_page(tsv_path)

    assert page.startswith("<!-- Auto-generated by")
    assert "do not hand-edit" in page
    assert "# omop-onz-g mapping set" in page
    assert "Added: 1" in page
    assert "omop:Person" in page
    assert "onz-g:Client" in page


# --- generate_mapping_pages -------------------------------------------------


def test_generate_mapping_pages_generates_one_page_per_tsv(tmp_path: Path) -> None:
    build_dir = tmp_path / "build" / "mappings"
    docs_dir = tmp_path / "docs" / "mappings"
    build_dir.mkdir(parents=True)

    _write_tsv(build_dir, "omop-onz-g", _mapping_set(_mapping()))
    _write_tsv(
        build_dir,
        "other-pair",
        _mapping_set(_mapping(object_id="onz-g:Other")),
    )

    written = generate_mapping_pages(build_dir, docs_dir)

    assert sorted(p.name for p in written) == ["omop-onz-g.md", "other-pair.md"]
    assert (docs_dir / "omop-onz-g.md").exists()
    assert (docs_dir / "other-pair.md").exists()


def test_generate_mapping_pages_overwrites_existing_placeholder(
    tmp_path: Path,
) -> None:
    build_dir = tmp_path / "build" / "mappings"
    docs_dir = tmp_path / "docs" / "mappings"
    build_dir.mkdir(parents=True)
    docs_dir.mkdir(parents=True)

    placeholder_path = docs_dir / "omop-onz-g.md"
    placeholder_path.write_text(
        "This page is a placeholder and should not be trusted.\n"
    )

    _write_tsv(build_dir, "omop-onz-g", _mapping_set(_mapping()))

    generate_mapping_pages(build_dir, docs_dir)

    content = placeholder_path.read_text()
    assert "placeholder" not in content
    assert "# omop-onz-g mapping set" in content


def test_generate_mapping_pages_empty_build_dir_returns_empty_list(
    tmp_path: Path,
) -> None:
    build_dir = tmp_path / "build" / "mappings"
    docs_dir = tmp_path / "docs" / "mappings"
    build_dir.mkdir(parents=True)

    written = generate_mapping_pages(build_dir, docs_dir)

    assert written == []


def test_generate_mapping_pages_missing_build_dir_returns_empty_list(
    tmp_path: Path,
) -> None:
    build_dir = tmp_path / "build" / "does-not-exist"
    docs_dir = tmp_path / "docs" / "mappings"

    written = generate_mapping_pages(build_dir, docs_dir)

    assert written == []
    assert not docs_dir.exists()
