"""Generate `docs/mappings/*.md` pages from generated `build/mappings/*.sssom.tsv`.

Per AGENTS.md's docs-site design and plan.md todo #15, the published
mapping-set pages must share the same rendering code path as the PR report
(`mapping/report.py`), not a separate hand-written template. This module is
a thin wrapper around that renderer: for every `<name>.sssom.tsv` found
under a build directory, it loads the mapping set
(`report.load_mapping_set_tsv`), computes a "current state" diff against
`base=None` (per `diff_mapping_sets`'s documented convention: with no prior
version, every mapping renders as "added"), renders Markdown
(`report.render_markdown`), and writes it to `docs/mappings/<name>.md`,
overwriting whatever placeholder or previously generated page is there.

This intentionally iterates the build directory rather than hardcoding
`omop-onz-g`, so additional mapping sets are picked up automatically once
their `.sssom.tsv` is generated.
"""

from __future__ import annotations

import logging
from pathlib import Path

from sssom_rosetta.mapping.report import (
    diff_mapping_sets,
    load_mapping_set_tsv,
    render_markdown,
)

logger = logging.getLogger(__name__)

#: Prepended to every generated page so contributors know not to hand-edit it.
_GENERATED_HEADER = (
    "<!-- Auto-generated by `rosetta docs generate-mapping-pages` from the "
    "corresponding build/mappings/*.sssom.tsv -- do not hand-edit. -->\n\n"
)


def _title_for(name: str) -> str:
    """Derive a page title from a mapping set's file stem, e.g. 'omop-onz-g'."""
    return f"{name} mapping set"


def generate_mapping_page(tsv_path: Path) -> str:
    """Render one mapping set's docs page Markdown from its generated `.sssom.tsv`.

    Args:
        tsv_path: Path to a generated `<name>.sssom.tsv` file.

    Returns:
        The full Markdown text for `docs/mappings/<name>.md`, including the
        auto-generated-file header note.
    """
    mapping_set = load_mapping_set_tsv(tsv_path)
    diff = diff_mapping_sets(None, mapping_set)
    name = tsv_path.name.removesuffix(".sssom.tsv")
    body = render_markdown(diff, mapping_set=mapping_set, title=_title_for(name))
    return _GENERATED_HEADER + body


def generate_mapping_pages(build_dir: Path, docs_dir: Path) -> list[Path]:
    """Generate a docs page for every `*.sssom.tsv` found under `build_dir`.

    Args:
        build_dir: Directory containing generated `<name>.sssom.tsv` files
            (typically `build/mappings/`).
        docs_dir: Directory generated pages are written to (typically
            `docs/mappings/`), created if it doesn't exist yet.

    Returns:
        The list of Markdown file paths written, one per `.sssom.tsv` found,
        in sorted order. Returns an empty list if `build_dir` doesn't exist
        or contains no `.sssom.tsv` files.
    """
    if not build_dir.is_dir():
        logger.warning(
            "build directory %s does not exist; nothing to generate", build_dir
        )
        return []

    tsv_paths = sorted(build_dir.glob("*.sssom.tsv"))
    if not tsv_paths:
        logger.warning(
            "no .sssom.tsv files found under %s; nothing to generate", build_dir
        )
        return []

    docs_dir.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []
    for tsv_path in tsv_paths:
        name = tsv_path.name.removesuffix(".sssom.tsv")
        page_path = docs_dir / f"{name}.md"
        page_path.write_text(generate_mapping_page(tsv_path))
        written.append(page_path)

    return written
